name: Build
on:
  push:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Display the path
        run: echo $PATH
        shell: bash 

