name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Display the path
        run: echo $PATH
        shell: bash 
      - name: GitHub context
        run: echo ${{ github.context }}

