name: CI
on:
  push:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Display the path
        run: echo $PATH
        shell: bash 

