on:
  pull_request:
    
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow failed'

