name: semantic-release
on:
  push:
    branches:
     - main
  pull_request:
  workflow_run:
    workflows: [CI]
    types: [completed]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check conslusion
        run: echo ${{ github.event.workflow_run.conslusion }}
  # This workflow contains a single job called "build"
  semantic-release:
    uses: mondo192/semantic-release-action/.github/workflows/main.yml@v1.0.0
    secrets: inherit
