on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_run:
    workflows: 
      - Build
    types: 
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ github.ref != 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }} && ${{ github.ref != 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow failed'

