# This is a basic workflow to help you get started with Actions

name: semantic-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
     - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_run:
    workflows: [ci]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mondo192/semantic-release-action/.github/workflows/main.yml@v1.0.0
    secrets: inherit
